export const db = {
  seats: [
    { id: 1, label: 'A1', status: 'available', row: 1, column: 1 },
    { id: 2, label: 'A2', status: 'available', row: 1, column: 2 },
    { id: 3, label: 'A3', status: 'available', row: 1, column: 3 },
    { id: 4, label: 'A4', status: 'booked', row: 1, column: 4 },
    { id: 5, label: 'A5', status: 'available', row: 1, column: 5 },
    { id: 6, label: 'A6', status: 'available', row: 1, column: 6 },
    { id: 7, label: 'A7', status: 'booked', row: 1, column: 7 },
    { id: 8, label: 'A8', status: 'available', row: 1, column: 8 },
    { id: 9, label: 'A9', status: 'available', row: 1, column: 9 },
    { id: 10, label: 'A10', status: 'available', row: 1, column: 10 },
    { id: 11, label: 'B1', status: 'available', row: 2, column: 1 },
    { id: 12, label: 'B2', status: 'available', row: 2, column: 2 },
    { id: 13, label: 'B3', status: 'booked', row: 2, column: 3 },
    { id: 14, label: 'B4', status: 'available', row: 2, column: 4 },
    { id: 15, label: 'B5', status: 'available', row: 2, column: 5 },
    { id: 16, label: 'B6', status: 'available', row: 2, column: 6 },
    { id: 17, label: 'B7', status: 'available', row: 2, column: 7 },
    { id: 18, label: 'B8', status: 'booked', row: 2, column: 8 },
    { id: 19, label: 'B9', status: 'available', row: 2, column: 9 },
    { id: 20, label: 'B10', status: 'available', row: 2, column: 10 },
    { id: 21, label: 'C1', status: 'available', row: 3, column: 1 },
    { id: 22, label: 'C2', status: 'booked', row: 3, column: 2 },
    { id: 23, label: 'C3', status: 'available', row: 3, column: 3 },
    { id: 24, label: 'C4', status: 'available', row: 3, column: 4 },
    { id: 25, label: 'C5', status: 'available', row: 3, column: 5 },
    { id: 26, label: 'C6', status: 'available', row: 3, column: 6 },
    { id: 27, label: 'C7', status: 'booked', row: 3, column: 7 },
    { id: 28, label: 'C8', status: 'available', row: 3, column: 8 },
    { id: 29, label: 'C9', status: 'available', row: 3, column: 9 },
    { id: 30, label: 'C10', status: 'available', row: 3, column: 10 },
    { id: 31, label: 'D1', status: 'available', row: 4, column: 1 },
    { id: 32, label: 'D2', status: 'available', row: 4, column: 2 },
    { id: 33, label: 'D3', status: 'available', row: 4, column: 3 },
    { id: 34, label: 'D4', status: 'available', row: 4, column: 4 },
    { id: 35, label: 'D5', status: 'booked', row: 4, column: 5 },
    { id: 36, label: 'D6', status: 'available', row: 4, column: 6 },
    { id: 37, label: 'D7', status: 'available', row: 4, column: 7 },
    { id: 38, label: 'D8', status: 'booked', row: 4, column: 8 },
    { id: 39, label: 'D9', status: 'available', row: 4, column: 9 },
    { id: 40, label: 'D10', status: 'available', row: 4, column: 10 },
    { id: 41, label: 'E1', status: 'available', row: 5, column: 1 },
    { id: 42, label: 'E2', status: 'available', row: 5, column: 2 },
    { id: 43, label: 'E3', status: 'available', row: 5, column: 3 },
    { id: 44, label: 'E4', status: 'booked', row: 5, column: 4 },
    { id: 45, label: 'E5', status: 'available', row: 5, column: 5 },
    { id: 46, label: 'E6', status: 'available', row: 5, column: 6 },
    { id: 47, label: 'E7', status: 'available', row: 5, column: 7 },
    { id: 48, label: 'E8', status: 'available', row: 5, column: 8 },
    { id: 49, label: 'E9', status: 'booked', row: 5, column: 9 },
    { id: 50, label: 'E10', status: 'available', row: 5, column: 10 },
    { id: 51, label: 'F1', status: 'available', row: 6, column: 1 },
    { id: 52, label: 'F2', status: 'booked', row: 6, column: 2 },
    { id: 53, label: 'F3', status: 'available', row: 6, column: 3 },
    { id: 54, label: 'F4', status: 'available', row: 6, column: 4 },
    { id: 55, label: 'F5', status: 'available', row: 6, column: 5 },
    { id: 56, label: 'F6', status: 'available', row: 6, column: 6 },
    { id: 57, label: 'F7', status: 'available', row: 6, column: 7 },
    { id: 58, label: 'F8', status: 'available', row: 6, column: 8 },
    { id: 59, label: 'F9', status: 'booked', row: 6, column: 9 },
    { id: 60, label: 'F10', status: 'available', row: 6, column: 10 },
    { id: 61, label: 'G1', status: 'available', row: 7, column: 1 },
    { id: 62, label: 'G2', status: 'available', row: 7, column: 2 },
    { id: 63, label: 'G3', status: 'available', row: 7, column: 3 },
    { id: 64, label: 'G4', status: 'available', row: 7, column: 4 },
    { id: 65, label: 'G5', status: 'booked', row: 7, column: 5 },
    { id: 66, label: 'G6', status: 'available', row: 7, column: 6 },
    { id: 67, label: 'G7', status: 'available', row: 7, column: 7 },
    { id: 68, label: 'G8', status: 'available', row: 7, column: 8 },
    { id: 69, label: 'G9', status: 'available', row: 7, column: 9 },
    { id: 70, label: 'G10', status: 'booked', row: 7, column: 10 }
  ],
  students: [
    {
      id: 'stu-1001',
      name: 'Aditi Sharma',
      email: 'aditi@avani.com',
      phone: '+91 9876543210',
      membershipPlan: 'monthly',
      feePaid: 2200,
      feeTotal: 2800,
      dueDate: '2026-10-10',
      seatId: 4,
      attendance: { in: '2026-09-22T09:05:00', out: null },
      qrCode: 'AVANI-1001',
      status: 'active'
    },
    {
      id: 'stu-1002',
      name: 'Rahul Verma',
      email: 'rahul@avani.com',
      phone: '+91 9988776655',
      membershipPlan: 'quarterly',
      feePaid: 4800,
      feeTotal: 6200,
      dueDate: '2026-11-12',
      seatId: 7,
      attendance: { in: '2026-09-22T08:40:00', out: null },
      qrCode: 'AVANI-1002',
      status: 'active'
    }
  ],
  offers: [
    { id: 1, title: 'Festival Offer', description: 'Flat 20% off on quarterly memberships', discount: 20, active: true },
    { id: 2, title: 'Night Study Boost', description: 'Extended evening slots and free mentor desk access', discount: 15, active: true }
  ],
  complaints: [
    {
      id: 'c-1',
      studentId: 'stu-1001',
      category: 'AC',
      message: 'Air conditioner is not cooling near seat A4.',
      status: 'open',
      createdAt: '2026-09-22T08:30:00Z'
    }
  ]
};
